In [4]:
import torch

In [5]:
x=torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [7]:
x.requires_grad_(True)
x.grad

In [8]:
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [9]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [10]:
x.grad == 4*x

tensor([True, True, True, True])

In [13]:
x.grad.zero_()
y=x*x
y.backward()
x.grad

RuntimeError: grad can be implicitly created only for scalar outputs

In [12]:
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])