In [5]:
import torch 
import random

In [16]:
def data_iter(batch_size, features, labels):
    num_examples = len(features)  # 计算样本数量
    indices = list(range(num_examples))  # 创建样本索引列表
    random.shuffle(indices)  # 随机打乱索引
    for i in range(0, num_examples, batch_size):
        batch_indices = torch.tensor(indices[i:min(i + batch_size, num_examples)])  # 将索引转换为张量
        print(indices[i:min(i + batch_size, num_examples)])  # 将索引转换为张量)
        yield features[batch_indices], labels[batch_indices]  # 返回当前批次的特征和标签

In [17]:
features = torch.tensor(list(range(0,100)))
labels = torch.tensor(list(range(100,200)))

In [18]:
data_iter1 = data_iter(10,features,labels)

In [19]:
next(data_iter1)

[66, 74, 18, 15, 93, 7, 79, 56, 84, 3]


(tensor([66, 74, 18, 15, 93,  7, 79, 56, 84,  3]),
 tensor([166, 174, 118, 115, 193, 107, 179, 156, 184, 103]))

In [21]:
features[torch.tensor([1,2])]

tensor([1, 2])

In [23]:
list2 = 1:10:2

SyntaxError: invalid syntax (2328608817.py, line 1)