In [16]:
import torch

In [17]:
a = torch.tensor(-1)#0维向量
len(a)

TypeError: len() of a 0-d tensor

In [18]:
b = torch.tensor([1,-1])#2维向量 == [[1],[-1]]
print('b=',b,'\t\tlen(b)',len(b),'\tb.dim  ',b.dim(),'\tb.shape',b.shape)
c = torch.tensor([[1,-1]])
print('c=',c,'\t\tlen(c)',len(c),'\tc.dim  ',c.dim(),'\tc.shape',c.shape)
d = torch.tensor([[1],[-1]])
print('d=',d,'\t\t\tlen(d)',len(d),'\td.dim  ',d.dim(),'\td.shape',d.shape)

b= tensor([ 1, -1]) 		len(b) 2 	b.dim   1 	b.shape torch.Size([2])
c= tensor([[ 1, -1]]) 		len(c) 1 	c.dim   2 	c.shape torch.Size([1, 2])
d= tensor([[ 1],
        [-1]]) 			len(d) 2 	d.dim   2 	d.shape torch.Size([2, 1])


In [19]:
# 创建一个2D张量
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])

# 打印张量的维度数和形状中的最大数
print("张量的维度数:", tensor_2d.dim())  # 输出 2
print("张量形状中的最大数:", max(tensor_2d.shape))  # 输出 3


张量的维度数: 2
张量形状中的最大数: 3


In [23]:
print(a,'\t\t\t',a.shape)
print(b,'\t\t\t',b.shape)
print(c,'\t\t\t',c.shape)
print(d,'\t\t\t',d.shape)

tensor(-1) 			 torch.Size([])
tensor([ 1, -1]) 			 torch.Size([2])
tensor([[ 1, -1]]) 			 torch.Size([1, 2])
tensor([[ 1],
        [-1]]) 			 torch.Size([2, 1])


## 总结
1. len(tensor) == tensor.shape[0] 
2. tensor.dim == len(tensor.shape)