In [11]:
import numpy as np

In [12]:
features = np.arange(5).reshape(-1,1)
print(features)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [13]:
exponents_1d = np.arange(5)
exponents_2d = np.arange(5).reshape(1,-1)
exponents_1d,exponents_2d

(array([0, 1, 2, 3, 4]), array([[0, 1, 2, 3, 4]]))

In [14]:
print(np.power(features,exponents_1d))
print(np.power(features,exponents_2d))

[[  1   0   0   0   0]
 [  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]]
[[  1   0   0   0   0]
 [  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]]


广播的规则:

- 让所有输入数组都向其中形状最长的数组看齐，形状中不足的部分通过在前面加 1 补齐。
- 输出数组的形状是输入数组形状的各个维度上的最大值。
- 如果输入数组的某个维度和输出数组的对应维度的长度相同或者其长度为 1 时，这个数组能够用来沿着此维度进行计算，否则出错。
- 当输入数组的某个维度的长度为 1 时，沿着此维度运算时都用此维度上的第一组值。
