In [2]:
import torch

In [7]:
x = torch.arange(0,27,1).reshape((3,3,3))
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [9]:
x.sum(0)

tensor([[27, 30, 33],
        [36, 39, 42],
        [45, 48, 51]])

In [11]:
x.sum(0,keepdim=True)

tensor([[[27, 30, 33],
         [36, 39, 42],
         [45, 48, 51]]])

In [12]:
x.sum(1)

tensor([[ 9, 12, 15],
        [36, 39, 42],
        [63, 66, 69]])

In [13]:
x.sum(1,keepdim=True)

tensor([[[ 9, 12, 15]],

        [[36, 39, 42]],

        [[63, 66, 69]]])

: 