In [1]:
import torch

In [2]:
x = torch.arange(27).reshape(3,3,3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [3]:
x[[0,1,2],[0,0,0],[0,0,0]]

tensor([ 0,  9, 18])

In [4]:
x[:2,:2,:]

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 9, 10, 11],
         [12, 13, 14]]])

In [8]:
x[[0,1],[0,1],:]

tensor([[ 0,  1,  2],
        [12, 13, 14]])

: 

In [6]:
x[:, :2, :2]


tensor([[[ 0,  1],
         [ 3,  4]],

        [[ 9, 10],
         [12, 13]],

        [[18, 19],
         [21, 22]]])

In [7]:
x[[0,1,2],:2,:2]

tensor([[[ 0,  1],
         [ 3,  4]],

        [[ 9, 10],
         [12, 13]],

        [[18, 19],
         [21, 22]]])